### ISSUE TITLE
Add restart services command

### ISSUE THREAD

**Issue by ohryan** [deliciousbrains/spinupwp-cli#25]
Add support for `service` API endpoints. To enable this, add command for each of the services (`nginx`, `php`, `mysql`), command should accept server id or prompt for one if none provided.

Example:
```
spinupwp nginx:restart --server_id=1234
spinupwp php:restart --server_id=1234
spinupwp mysql:restart --server_id=1234
```

**Comment by A5hleyRich** [comment]
Another option:

```
spinupwp services:nginx --server_id=1234 --all
spinupwp services:php --server_id=1234 --all
spinupwp services:mysql --server_id=1234 --all
```

I'm also thinking the `--all` flag could be useful to restart a service on all servers.
