### ISSUE TITLE
Add site creation

### ISSUE THREAD

**Issue by ohryan** [deliciousbrains/spinupwp-cli#26]
Add a `sites:create` command. Initially this will only support the `wp` site type, with the following parameters:

| Option | Required | Default|
|--------|----------|--------|
|server_id|Y||
|domain|Y||
|site_user|N|auto-generated|
|database_name|N|auto-generated|
|database_username|N|auto-generated|
|database_password|N|auto-generated|
|wp_title|Y||
|wp_admin_user|Y||
|wp_admin_email|Y||
|wp_admin_password|N|auto-generated|

Any RESET API options not listed will use the API's default value. 

When the wizard is being used auto-generated values will be presented as defaults. 

When parameters are passed auto-generated values will be used for any optional parameter which have been omitted.

**Comment by A5hleyRich** [comment]
Looks good. What about supporting the blank installation method from the get-go? That doesn't feel like much work and will lay the groundwork for the conditional validation logic when we add support for git installations. I also think we're going to need these optional parameters:

| Option | Required | Default|
|--------|----------|--------|
|php_version|N|auto-generated|
|page_cache_enabled|N|true|
|https_enabled|N|true|

**Comment by ohryan** [comment]
Should each installation type be different commands (i.e. `site:create, site:create-blank`)? 

Each type of site has a slightly different set of required options (ex. WP sites require admins, blank sites do not), so we won't be able to enforce these options via the command. They all need to be optional. This may also `--help` text awkward if we have to explain the optional cases. And `handle()` function will be more complex.
