### ISSUE TITLE
Documentation of the use of --fields should state that any fields from the API can be used.

### ISSUE THREAD

**Issue by rosswintle** [deliciousbrains/spinupwp-cli#35]
## Overview

The README for the SpinupWP CLI shows the use of `--fields` and gives examples for several `:list` commands.

It does not state which fields are available.

In my experimenting I was able to get pretty much any field from the SpinupWP API response. For example, the following worked:

 - ` backups.retention_period`
 - `basic_auth.username`
 - `git.branch`

Details of this should be documented in the readme so that people are clear what fields are available.

## Related

n/a

## Acceptance Criteria

- [ ] Documentation explains what fields are available when using `--fields`

**Comment by A5hleyRich** [comment]
Resolved in https://github.com/deliciousbrains/spinupwp-cli/commit/fdb7c0b7e2520bc22f0f04cb515f387485091add
