### ISSUE TITLE
Using --format should output the requested format (this should also be documented)

### ISSUE THREAD

**Issue by rosswintle** [deliciousbrains/spinupwp-cli#36]
## Current Outcome
Currently... if I use `--format=xml` (or specify any format with `--format`) I get JSON output.

## Desired Outcome
Ideally... if I use `--format=xml` I would get XML output. And so on.

I'd also like to see the use of `--format` in the documentation, even if it only works for JSON. The reason for this is that people will probably want to use the CLI for automation, and this will require an easily computer-readable output format such as JSON.

## Steps to Reproduce

1. Install and configure the SpinupWP CLI
2. Enter `spinupwp sites:list --format=xml`

## Acceptance Criteria

- [ ] `--format` options should have the following input description:

> The output format (table, or json)

ALSO:

- [ ] The CLI README shows examples of using `--format`

**Comment by A5hleyRich** [comment]
Let's remove the Laravel Zero default `--format` option.

**Comment by rosswintle** [comment]
👍 Though I think that having JSON output as an option is pretty important! So would be good to have it back in future.

**Comment by A5hleyRich** [comment]
@rosswintle to clarify, JSON is an option and always will be. The confusion here is the disparity between the format flags at a global level:

![CleanShot 2022-03-02 at 10 48 51@2x](https://user-images.githubusercontent.com/1422996/156347609-f56646c4-40f9-40d4-a469-a7488b2fdb27.png)

vs command level:

![CleanShot 2022-03-02 at 10 50 14@2x](https://user-images.githubusercontent.com/1422996/156347825-7126cc29-b298-4a95-bcb2-4c5fbd8a2a62.png)

We didn't see the need for XML or MD format, so we only implemented table and JSON formats.

Thinking about this some more, this isn't a bug and I don't think we need to remove the global `--format` flag. The solution is to add a description to command-level `--format` flags explaining the formats that are supported.
